# Generated by Django 4.2.17 on 2025-09-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_name",
                    models.CharField(max_length=200, verbose_name="房产名称"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="销售价格"
                    ),
                ),
                ("sale_date", models.DateField(verbose_name="销售日期")),
                (
                    "buyer_name",
                    models.CharField(max_length=100, verbose_name="买家姓名"),
                ),
                (
                    "seller_name",
                    models.CharField(max_length=100, verbose_name="卖家姓名"),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, null=True, verbose_name="佣金"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "销售记录",
                "verbose_name_plural": "销售记录",
                "ordering": ["-sale_date"],
            },
        ),
    ]
